### PR TITLE
use the filter with Logstash 5.x

### PR DESCRIPTION
**Pull request by vktor18**
I simply changed few things to make this filter supporting logstash 5.x 

based on -->[https://github.com/elastic/logstash/blob/5.x/docs/static/breaking-changes.asciidoc#ruby-filter-and-custom-plugin-developers](url)

Thanks!

### CODE REVIEW

**Comment by vktor18** [comment]
i don't understand why travis is having trouble..

**Comment by jsvd** [comment]
travis is having some issues https://www.traviscistatus.com/

**Comment by bitsofinfo** [comment]
This PR should also be incorporated  https://github.com/logstash-plugins/logstash-filter-cipher/pull/11

**Comment by vktor18** [comment]
Hi guys, I want to report a problem that I'm facing now using the cipher filter.

As far as i use the filter with a basic configuration such as input from file, cipher filter for encrypting a field and an output file, works pretty well.

When I switch to a pipeline configuration more complex (3 inputs from rabbit, complex logic filter, output elasticsearch and file) it returns an exception 

`Exception catch on cipher filter {:event=>2017-03-02T10:46:47.576Z %{host} %{message}, :error=>#<NoMethodError: undefined method `iv=' for nil:NilClass>}`

The fact that the filter works fine using another pipeline makes me confused about what possible error I'm facing here....

Any suggestions?

**Comment by vktor18** [comment]
Ok the issue is definitely when I use rabbitmq as input for logstash...

**Comment by vktor18** [comment]
sorry, I fixed the issue. It was missing a configuration for rabbitmq input

**Pull request closed without merging**
